app = "financas-pessoais-mmm"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

[[mounts]]
  source = "financas_data"
  destination = "/data"

[env]
  FINANCAS_DATA_DIR = "/data"
